# crate table employees
CREATE TABLE employees (
    id INT NOT NULL AUTO_INCREMENT,
    em_name VARCHAR(50) NOT NULL,
    nrc VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

# insert data into employees
INSERT INTO employees (em_name, nrc, phone, address) VALUES ('Aung Aung', 'np-021345', '09-5555221', 'Yangon'),
('Mg Aung', 'np-021345', '09-5555221', 'Yangon'),
('Ko Ko', 'np-021345', '09-5555221', 'Mangadla'),
('Ko Aung', 'np-021345', '09-5555221', 'Yangon'),
('Aung KO', 'np-021345', '09-5555221', 'Yangon');
# crate table hobbies
CREATE TABLE hobbies (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    employee_id INT NOT NULL,
    PRIMARY KEY (id)
);

# insert data into hobbies
INSERT INTO hobbies (name, employee_id) VALUES ('Football', 1),
('Basketball', 1),
('Volleyball', 2),
('Badminton', 3),
('Table Tennis', 4),
('Swimming', 5),
('Tennis', 6),
('Cycling', 7),
('Running', 8),
('Hiking', 19),
('Skiing', 10);

# crate table emp_hobbies
CREATE TABLE emp_hobbies (
    id INT NOT NULL AUTO_INCREMENT,
    employee_id INT NOT NULL,
    hobby_id INT NOT NULL,
    PRIMARY KEY (id)
);

# insert data into emp_hobbies


-- INSERT INTO hobbies (name) VALUES ('Football'),
-- ('Basketball'),
-- ('Volleyball'),
-- ('Badminton'),
-- ('Table Tennis'),
-- ('Swimming'),
-- ('Tennis'),
-- ('Golf'),
-- ('Cycling'),
-- ('Running'),
-- ('Hiking'),
-- ('Skiing'),
-- ('Soccer'),
-- ('Baseball'),
-- ('Softball'),
-- ('Bowling'),
-- ('Dancing'),
-- ('Gymnastics'),
-- ('Boxing'),
-- ('Martial Arts'),
-- ('Wrestling'),
-- ('Fencing'),
-- ('Archery'),
-- ('Horseback Riding'),
-- ('Skating'),
-- ('Surfing'),
-- ('Kayaking'),
-- ('Climbing'),
-- ('Sailing'),
-- ('Scuba Diving'),
-- ('Snorkeling'),
-- ('Fishing'),
-- ('Hunting'),
-- ('Gardening'),
-- ('Cooking'),
-- ('Reading'),
-- ('Writing'),
-- ('Painting'),
-- ('Drawing'),
-- ('Singing'),
-- ('Playing Music'),
-- ('Playing an Instrument'),
-- ('Photography'),
-- ('Video Games'),
-- ('Board Games'),
-- ('Puzzles'),
-- ('Collecting'),
-- ('Traveling'),
-- ('Watching Sports'),
-- ('Watching Movies'),
-- ('Watching TV'),
-- ('Watching Plays'),
-- ('Attending Concerts'),
-- ('Attending Sporting Events'),
-- ('Attending Theater'),
-- ('Attending Fairs'),
-- ('Attending Festivals'),
-- ('Attending Parades'),
-- ('Attending Rallies'),
-- ('Attending Political Events'),
-- ('Attending Religious Events'),
-- ('Attending Social Events'),
-- ('Attending Fundraisers'),
-- ('Attending Parties'),
-- ('Attending Reunions'),
-- ('Attending Weddings'),
-- ('Attending Funerals'),
-- ('Attending Barbecues'),
-- ('Attending Picnics'),
-- ('Attending Dances'),
-- ('Attending Proms'),
-- ('Attending School Events'),
-- ('Attending School Functions'),
-- ('Attending School Dances'),
-- ('Attending School Reunions'),
-- ('Attending School Sports Events'),
-- ('Attending School Plays'),
-- ('Attending School Concerts'),
-- ('Attending School Fundraisers'),
-- ('Attending School Parties'),
-- ('Attending School Picnics'),
-- ('Attending School Barbecues'),
-- ('Attending School Dances'),
-- ('Attending School Proms'),
-- ('Attending School Reunions'),
-- ('Attending School Social Events'),
-- ('Attending School Weddings'),
-- ('Attending School Funerals'),
-- ('Attending School Rallies'),
-- ('Attending School Parades'),
-- ('Attending School Fairs'),
-- ('Attending School Festivals'),
-- ('Attending School Political Events');