<?php
namespace App\AmkOnlineShop\Databases;

class StateModel
{
 // country list
 public static function StateOptions()
 {
  // State list with country code and country name asc order with country name
  return
  [
   // american state 50
   'AL' => 'Alabama',
   'AK' => 'Alaska',
   'AZ' => 'Arizona',
   'AR' => 'Arkansas',
   'CA' => 'California',
   'CO' => 'Colorado',
   'CT' => 'Connecticut',
   'DE' => 'Delaware',
   'FL' => 'Florida',
   'GA' => 'Georgia',
   'HI' => 'Hawaii',
   'ID' => 'Idaho',
   'IL' => 'Illinois',
   'IN ' => 'Indiana (IN)',
   'IA ' => 'Iowa (IA)',
   'KS'  => 'Kansas (KS)',
   'KY ' => 'Kentucky (KY)',
   'LA' => 'Louisiana (LA)',
   'ME' => 'Maine (ME)',
   'MD' => 'Maryland (MD)',
   'MA ' => 'Massachusetts (MA)',
   'MI' => 'Michigan (MI)',
   'MN ' => 'Minnesota (MN)',
   'MS' => 'Mississippi (MS)',
   'MO ' => 'Missouri (MO)',
   'MT' => 'Montana (MT)',
   'NE' => 'Nebraska (NE)',
   'NV' => 'Nevada (NV)',
   'NH' => 'New Hampshire (NH)',
   'NJ' => 'New Jersey (NJ)',
   'NM' => 'New Mexico (NM)',
   'NY' => 'New York (NY)',
   'NC' => 'North Carolina (NC)',
   'ND' => 'North Dakota (ND)',
   'OH' => 'Ohio (OH)',
   'OK' => 'Oklahoma (OK)',
   'OR' => 'Oregon (OR)',
   'PA' => 'Pennsylvania (PA)',
   'RI' => 'Rhode Island (RI)',
   'SC' => 'South Carolina (SC)',
   'SD' => 'South Dakota (SD)',
   'TN' => 'Tennessee (TN)',
   'TX' => 'Texas (TX)',
   'UT' => 'Utah (UT)',
   'VT' => 'Vermont (VT)',
   'VA' => 'Virginia (VA)',
   'WA' => 'Washington (WA)',
   'WV' => 'West Virginia (WV)',
   'WI' => 'Wisconsin (WI)',
   'WY' => 'Wyoming (WY)',
   // Myanmar state 14
   'AY' => 'Ayeyarwady Region (AY)',
   'BG' => 'Bago Region (BG)',
   'CN' => 'Chin State (CN)',
   'KC' => 'Kachin State (KC)',
   'KK' => 'Kayah State (KK)',
   'KN' => 'Kayin State (KN)',
   'MG' => 'Magway Region (MG)',
   'MD' => 'Mandalay Region (MD)',
   'MN' => 'Mon State (MN)',
   'RA' => 'Rakhine State (RA)',
   'SG' => 'Sagaing Region (SG)',
   'SH' => 'Shan State (SH)',
   'TN' => 'Tanintharyi Region (TN)',
   'YG' => 'Yangon Region (YG)',
   // Afghanistan state list
   'Fayzabad' => 'Badakhshan ',
   'Qala i Naw' =>       'Badghis ',
   'Pul-i Khumri' =>       'Baghlan ',
   'Mazar-i-Sharif' =>       'Balkh',
   'Bamyan' =>       'Bamyan ',
   'Nili' =>       'Daykundi ',
   'Farah' =>       'Farah ',
   'Maimana' =>       'Faryab ',
   'Ghazni' =>       'Ghazni ',
   'Chaghcharan' =>       'Ghor ',
   'Lashkar Gah' =>       'Helmand ',
   'Herat' =>       'Herat ',
   'Sheberghan' =>       'Jowzjan ',
   'Kabul' =>       'Kabul',
   'Kandahar' => 'Kandahar',
   'MahMud-e Raqi' => 'Kapisa ',
   'Khost' => 'Khost ',
   'Asadabad' => 'Kunar ',
   'Kunduz' => 'Kunduz ',
   'Mehtar Lam' => 'Laghman ',
   'Pul-e Alam' => 'Logar ',
   'Jalalabad' => 'Nangarhar ',
   'Zaranj' => 'Nimruz ',
   'Parun' => 'Nuristan ',
   'Sharana' => 'Paktika ',
   'Gardez' => 'Paktiya ',
   'Panjshir' => 'Panjshir ',
   'Charikar' => 'Parwan ',
   'Aybak' => 'Samangan ',
   'Sar-e Pol' => 'Sar-e Po- ',
   'Taluqan' => 'Takhar ',
   'Tarin Kowt' => 'Urozgan ',
   'Maidan Shar' => 'Wardak ',
   'Qalat' => 'Zabul ',
   
  ];

 }
}